DIST_NUM = "district number"
DIST_POP = "district population"
IN_ED_CODE = 0
# change use of IN_ED_NAMEE to IN_ED_NAMEF for french name
IN_ED_NAMEE = 1
IN_ED_NAMEF = 2
IN_POPULATION = 3
SEP = ","
DIST_FILE_NAME = "ED-Canada_2021"
VOTE_FILE_NAME = "pollbypoll_bureauparbureau"
VOTE_FILE_DIRECTORY = "pollbypoll_bureauparbureauCanada\\"
FILE_TYPE = '.csv'
CANADATE_END = -3
CANADATE_START = 4
CANADATE_HEAD_SIZE = 4
CANADATE_POS_F = 6
CANADATE_POS_L = 5
SPACE_SEP = ' '
TAB = '\t'
CANADATE_FILE_NAME = 'candidates.txt'
POL_PARTY = 3